name: Compile and Upload LaTeX Files

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive' # This ensures that submodules are recursively initialized and updated

    - name: Build TeXLive Docker 
      run: |
        docker build -t my-latex-image .
    - name: Compile LaTeX files
      run: |
        docker run --rm -v $PWD:/data my-latex-image
    - name: Move PDFs to correct location
      run: |
        mkdir docs/worksheets
        find . -name '*.pdf' -not -path '*/Figures/*' -exec sh -c '
          for FI do
            echo "Moving $FI to docs/worksheets folder"
            mv "$FI" docs/worksheets
          done
        ' exec-sh {} +
    - name: Edit webpages to include links for those pdfs
      run: |
        cd docs
        write_section_links() {
          DIR_NAME="$1"
          OUTPUT_FILENAME="$2"
          OUTPUT_SECTION_TITLE="$3"
          OUTPUT_LINK_PREFIX="$4"
          printf "## $OUTPUT_SECTION_TITLE\n" >> "$OUTPUT_FILENAME"
          for FNAME in *; do
            NAME="$OUTPUT_LINK_PREFIX""$FNAME"
            FPATH="$DIR_NAME/$FNAME"
            printf "[$NAME]($FPATH)  \n" >> "$OUTPUT_FILENAME" # Two spaces before \n tells Markdown to generate <br />
          done
          printf "\n" >> "$OUTPUT_FILENAME"
        }
        write_section_links "worksheets" "worksheets.md" "Math 115 Worksheets" ""
        cd ..
    - name: Deploy PDFs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        enable_jekyll: true
